Debian package builder has been modified:
   Now it restart pmacct and tomcat daemons.
   
   The debian post install script turns of java security in tomcat config file if the user accept to do that.
   
   Mysql dependency have been added.
   
   

git-svn-id: https://svn.code.sf.net/p/pmgraph/code/pmgraph@163 903098bd-d3be-4b5e-9df1-ec1ba492e1ff

diff --git a/debian/pmgraph.postinst b/debian/pmgraph.postinst
--- a/debian/pmgraph.postinst
+++ b/debian/pmgraph.postinst
@@ -17,7 +17,6 @@ PASSWD=$RET
 # Create database and user.
 echo Creating Mysql data base...
 mysql -u root -p$PASSWD < /usr/share/pmgraph/conf/pmacct-create-db_v6.mysql
-echo mysql -u root -p$PASSWD < /usr/share/pmgraph/conf/pmacct-create-db_v6.mysql
 echo -e \\t* pmacct database create in your mysql server.
 echo -e \\t* pmacct user created with default password = 'secret' you should change this password, if you do so dont forget to change de password in the pmacctd.conf file.
 
@@ -35,3 +34,25 @@ if [ "$RET" = "true" ]; then
 		echo "TOMCAT5_SECURITY=no" >> /etc/default/tomcat5.5
 	fi
 fi
+
+# restart tomcat and pmacct server
+if [ -x "/etc/init.d/tomcat5.5" ]; then
+        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+                invoke-rc.d tomcat5.5 restart || exit $?
+        else
+                /etc/init.d/tomcat5.5 start || exit $?
+        fi
+fi
+
+if [ -x "/etc/init.d/pmacct" ]; then
+        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+                invoke-rc.d pmacct start || exit $?
+        else
+                /etc/init.d/pmacct start || exit $?
+        fi
+fi
+
+db_stop # in case invoke failes
+
+exit 0
+
